### ISSUE TITLE
放几张预览图

### ISSUE THREAD

**Issue by amokiel** [yumeTsukiiii/YumePixiv#1]
支持开发者，可以考虑放几张预览图，以供参考也好。加油吧！

**Comment by yumeTsukiiii** [comment]
谢谢w，这就放几张～

**Comment by amokiel** [comment]
> 谢谢w，这就放几张～

感谢回复，加油加油

**Comment by amokiel** [comment]
> 谢谢w，这就放几张～

看到了预览图，页面挺好看的，预计什么时候可以发Releases呢，很期待啊

**Comment by yumeTsukiiii** [comment]
> > 谢谢w，这就放几张～
> 
> 看到了预览图，页面挺好看的，预计什么时候可以发Releases呢，很期待啊

工作比较忙不好说qaq～等功能再完善些再发～

**Comment by amokiel** [comment]
> > > 谢谢w，这就放几张～
> > 
> > 
> > 看到了预览图，页面挺好看的，预计什么时候可以发Releases呢，很期待啊
> 
> 工作比较忙不好说qaq～等功能再完善些再发～

ok，加油，慢慢来吧，这倒是无需着急
